version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zammad-rag-ui:latest
    container_name: zammad-rag-ui
    depends_on:
      - qdrant
      - ollama
    ports:
      - "5000:5000"
    environment:
      # Pfade für Konfiguration und Caches (extern gemounted)
      ENV_FILE: /data/config/ticket_ingest.env
      PROMPTS_DIR: /data/config/prompts
      HUGGINGFACE_CACHE_DIR: /data/cache

      # App/Server Konfiguration
      WEBUI_HOST: 0.0.0.0
      WEBUI_PORT: 5000

      # Standard-Embedding-Modell (build-time preload erfolgt im Dockerfile)
      EMBED_MODEL: intfloat/multilingual-e5-base

      # Upstream-Defaults für lokale Compose-Nutzung (werden von ENV_FILE/Frontend überschrieben)
      QDRANT_URL: http://qdrant:6333
      OLLAMA_URL: http://ollama:11434
    volumes:
      - ./config:/data/config
      - ./cache:/data/cache
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      # Optionaler API-Key; wenn leer, ist Qdrant ohne Key erreichbar.
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY:-}
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=1h
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped